### ISSUE TITLE
how to launch it?

### ISSUE THREAD

**Issue by luismesas** [behalfinc/b2c#1]
Hi, thanks for this library, will be very useful. After installing it, how do to reformat a generated behave json file? can you add the command/usage on the README?

thanks

**Comment by andreybehalf** [comment]
Hi Luis,
The usage is simple you just need to import the b2c package into your code and pass your behave cucumber as parameter to the convert() function. 
Here's is example to make it clear:
```

import json
import b2c

with open('behave_json.json') as behave_json:
    cucumber_json = b2c.convert(json.load(behave_json))
```

I will add this info to the README as-well, thanks!

P.S
I hope I will have time during this week to create python script to simplify it for people who don't want/need to integrate the library into their development and just want to re-format already existing behave jsons. The script will receive as argument a behave json file and will output a new cucumber json file.
